Allow developers to move the Klaviyo\Reclaim\Block\Initialize block
klaviyo/magento2-klaviyo pull request #204
Opened 2022-08-19 11:51 UTC by kevinruscoe

Give the `Klaviyo\Reclaim\Block\Initialize` block a name giving theme developers the option of referencing the block and moving it elsewhere.

2022-08-19 18:02 UTC, tylerkemme approved these changes

2022-10-26 10:09 UTC, ihor-sviziev approved these changes

2022-10-26 17:45 UTC, cykolln requested changes
Hi - thanks for the contribution. Can you please update the Changelog to include this change under Unreleased, we can include this in the next release.

2022-10-31 19:49 UTC, cykolln approved these changes
Thanks for updating the changelog! This will be included in the upcoming release

2022-10-31 19:49 UTC, merged

2022-11-01 23:32 UTC, cykolln commented
This has been included in the latest release 4.0.7 @kevinruscoe thank you again for your contribution, we appreciate it!