Do not load not needed backend classes
klaviyo/magento2-klaviyo pull request #214
Opened 2022-10-25 15:22 UTC by ihor-sviziev

## Description
This PR replaces the backend context with the frontend one. Since this controller is used on frontend, it doesn't make any sense to create classes needed for backend, e.g. backend session which is part of this conext

## Manual Testing Steps

1.

## Pre-Submission Checklist:

- [ ] You've updated the CHANGELOG following the steps [here](https://github.com/klaviyo/magento2-klaviyo#making-updates)
- [ ] **Internal Only** - If this is a release, have you:
  - [ ] Updated the links in the CHANGELOG to point towards the new versions
  - [ ] Incremented the version in the following places: module.xml and composer.json

2022-10-25 15:24 UTC, invertedfjord approved these changes

2022-10-25 22:14 UTC, cykolln requested changes
Can you please update the changelog by adding this change under Unreleased - we can include it in the upcoming release.

2022-10-26 21:40 UTC, cykolln approved these changes

2022-10-26 21:40 UTC, merged

2022-11-01 23:33 UTC, cykolln commented
This has been included in the latest release 4.0.7, thank you for another contribution @ihor-sviziev - much appreciated!